# Generated by Django 6.0.1 on 2026-02-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='LibraryModel',
            new_name='Library',
        ),
    ]
