# Generated by Django 6.0.1 on 2026-02-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_delete_book', 'Can delete book'), ('can_change_book', 'Can change book')]},
        ),
    ]
